#!/bin/bash
####
# This file is intended to be included into the .bashrc file via 'source'
# This short script checks if the backup is currently running or if there was a
# backup since the last log on. 
####

# Get configuration
source /opt/duplicati_helper/duplicati.conf

# Set duplicati update policy
export AUTOUPDATER_Duplicati_POLICY=$UPDATE_POLICY

DUPLICATI_PIDS="${PID_DIR}${DUPLICATI_PID_PREFIX}.*"
SHUTDOWN_PID="${PID_DIR}${SHUTDOWN_PID_PREFIX}.pid"

# A horizontal line
HR="+-----+----------+---------------------+-------------------------------------------------+"

# Print table header
echo "B A C K U P  S T A T U S"

echo "$HR"
echo "|     |   Name   |        Time         |                     Status                      |"
echo "$HR"

# Prints a proper alligned line for the table
# $1 Prop column (optional, only '+' allowed max. length 3)
# $2 Name column (no spaces allowed, max. length 8)
# $3 Time column (no spaces allowed, max. length 19)
# $4 Status column (max. length 47)
printLine() {
    # Available spaces for column
    SPACES="                                                  "
    PROP_COL=2
    NAME_COL=8
    TIME_COL=19
    STAT_COL=47
    
    echo -n "| " 
    if [ "$1" == "+" ] ; then
        echo -n " + "
        shift
    else
        echo -n "   "
    fi
     
    echo -n " | "
    echo -n "$1 $SPACES" | head -c $NAME_COL 
    echo -n " | "
    shift
    echo -n "$1 $SPACES" | head -c $TIME_COL
    echo -n " | "
    shift
    echo -n "$@ $SPACES" | head -c $STAT_COL
    echo " |"
}

# Is duplicati running
if ls ${DUPLICATI_PIDS} 1> /dev/null 2>&1; then
    for f in ${DUPLICATI_PIDS} ; do
        FILE_DATE=$(stat -c '%y' $f)
        # Replace spaces
        FILE_DATE=${FILE_DATE// /_}
        # Get job name out of pid file name
        f="${f//${PID_DIR}${DUPLICATI_PID_PREFIX}.}"
        f="${f//.pid}"
        
        printLine $f $FILE_DATE "running"
        # Print running jobs
    done
    echo "$HR"
fi

# What is the status of previous backups?
if [ -e $BACKUP_STATUS_FILE ] ; then
    # Status describes, if the backup status was read earlier, if status is '+' it is an unread entry that needs to be marked read, '-' means that it was read earlier
    while read -r prop name time status ; do
        if [ "${prop}" == "+" ] ; then
            prop=""
            sed -i '/^\(-\|+\) '"${name}"' /d' ${BACKUP_STATUS_FILE} 
            echo "- ${name} ${time} ${status}" >> $BACKUP_STATUS_FILE
        fi
        printLine ${prop} ${name} ${time} ${status}
    done < "${BACKUP_STATUS_FILE}"
    echo "$HR"
fi

# Is a shutdown scheduled?
if [ -e $SHUTDOWN_PID ] && ps -p $(cat $SHUTDOWN_PID) > /dev/null ; then
    echo
    echo "## Shutdown is scheduled ##"
fi
